@Petfolio.API_HostAddress = https://localhost:7218

POST {{Petfolio.API_HostAddress}}/api/Pet/
Accept: application/json
Content-Type: application/json

{
  "name": "Atreus",
  "birthday": "2024-04-17T23:47:21.677Z",
  "pet": 1
}

###
